### PR TITLE
Feature/task 464 generic category infrastrucutre for concepts

### PR DESCRIPTION
**Pull request by franzTobiasDLR**
Regenerated source code and DMF artifacts of concepts with the new generic category based infrastructure.

### CODE REVIEW

**Comment by franzTobiasDLR** [comment]
Somehow this PR isn't yet updated properly... It still shows the changes and commits of PR #378

**Comment by SaMuellerDLR** [comment]
> 
> 
> Somehow this PR isn't yet updated properly... It still shows the changes and commits of PR #378

Have you tried merging with development?

**Comment by PhilMFischer** [comment]
The diff coverage is to low. Looks like the generated constructors of  new migrators are not covered. This is a bit strange, i thought that they are captured as well in the generated test cases. PLease check otherwise create a ticket for it.

**Comment by franzTobiasDLR** [comment]
> 
> 
> The diff coverage is to low. Looks like the generated constructors of new migrators are not covered. This is a bit strange, i thought that they are captured as well in the generated test cases. Please check otherwise create a ticket for it.

Just checked, the generated migrator tests only exectue the migrate(...) with the loaded concepts. Not with the previous migrator object. I will create a ticket for that.

**Comment by PhilMFischer** [comment]
> The diff coverage is to low. Looks like the generated constructors of new migrators are not covered. This is a bit strange, i thought that they are captured as well in the generated test cases. Please check otherwise create a ticket for it.
> 
> Just checked, the generated migrator tests only exectue the migrate(...) with the loaded concepts. Not with the previous migrator object. I will create a ticket for that: #581

Good, I think #581 should be closed before than. Shouldn't it?

**Comment by franzTobiasDLR** [comment]
> 
> 
> > The diff coverage is to low. Looks like the generated constructors of new migrators are not covered. This is a bit strange, i thought that they are captured as well in the generated test cases. Please check otherwise create a ticket for it.
> > Just checked, the generated migrator tests only exectue the migrate(...) with the loaded concepts. Not with the previous migrator object. I will create a ticket for that: #581
> 
> Good, I think #581 should be closed before than. Shouldn't it?

Really? Because 9 lines are not covered?

**Comment by PhilMFischer** [comment]
> The diff coverage is to low. Looks like the generated constructors of new migrators are not covered. This is a bit strange, i thought that they are captured as well in the generated test cases. Please check otherwise create a ticket for it.
> Just checked, the generated migrator tests only exectue the migrate(...) with the loaded concepts. Not with the previous migrator object. I will create a ticket for that: #581
> 
> Good, I think #581 should be closed before than. Shouldn't it?
> 
> Really? Because 9 lines (out of 183 changed files) are not covered?

Not 100% sure. CodeCovs calculations are not clear to me. I think it really compares how much has changed (not just files) and checks how much of this change is covered. I think that is what they call the "patch". The "branch" seems to give green lights now.

**Pull request merged**
