### PR TITLE
Integrate author verification into build process

### PR DESCRIPTION
**Pull request by ghost**
- [x] Trying to iontegrate authors check into build process.
- [x] Still need to integrate CLA documents.
- [x] Still need to add data privacy declaration.
- [x] Have to update readme file to explain what is going on.

### CODE REVIEW

**Comment by DLRSCMnS** [comment]
:warning: Unknown authors in commit History :warning:

**Comment by DLRSCMnS** [comment]
:warning: Unknown authors in commit History :warning:

**Review by DLRSCMnS — CHANGES_REQUESTED** [review]
bad

**Review by DLRSCMnS — DISMISSED** [review]
Not happy yet

**Review by DLRSCMnS — CHANGES_REQUESTED** [review]
Need a Change

**Review by DLRSCMnS — DISMISSED** [review]
Now its good

**Review by DLRSCMnS — CHANGES_REQUESTED** [review]
Author Verification Report 
---------------------------

:x: Some Authors in commit History without CLA :x: 
:warn: .mailmap file has been changed :warn: 
:warn: known_authors.txt file has been changed :warn: 
:warn: The author of the Pull Request has no CLA :warn:

**Review by DLRSCMnS — CHANGES_REQUESTED** [review]
Author Verification Report 
---------------------------

:x: Some Authors in commit History without CLA :x: 
:warn: .mailmap file has been changed :warn: 
:warn: known_authors.txt file has been changed :warn: 
:warn: The author of the Pull Request has no CLA :warn:

**Review by DLRSCMnS — DISMISSED** [review]
Author Verification Report 
---------------------------

:x: Some Authors in commit History without CLA :x: 
:warning: .mailmap file has been changed :warning: 
:warning: known_authors.txt file has been changed :warning: 
:warning: The author of the Pull Request has no CLA :warning:

**Review by andriikovalov-dlr — APPROVED** [review]
If it's up to us, I'd suggest to reduce the requested information to absolute minimum - e.g. make telephone and contact email optional.

**Review by franzTobiasDLR — APPROVED** [review]

**Pull request merged**
