### PR TITLE
WIP: Remergin - Hotfix - Respecting ignored folders for SVN commit

### PR DESCRIPTION
**Pull request by andriikovalov-dlr**
# Remerging a hotfix to development

- Changed SVN UNVERSIONED filter to NEW (unversioned accepts ignored files)
- Changed svn check from project parent to project itself
- Added a test for ignoring

### CODE REVIEW

**Comment by PhilMFischer** [comment]
#932 is a kind of duplicate to this Merge request. Can you please clarify?

**Review by PhilMFischer — CHANGES_REQUESTED** [review]
See Comments

**Comment by andriikovalov-dlr** [comment]
> 
> 
> #932 is a kind of duplicate to this Merge request. Can you please clarify?

One is into development, and another is into LTS for a hotfix release

**Comment by PhilMFischer** [comment]
> 
> 
> See Comments

Ok i have seen it is the remerge into development line.

**Comment by andriikovalov-dlr** [comment]
This fix will be merged to development with the remerging of the integration branch, no separate pull request needed.

**Pull request closed without merging**
