### PR TITLE
Added new issue template for hot fix releases

### PR DESCRIPTION
**Pull request by ghost**
- Added a new issue template for hotfix releases.
- Adjusted the standard release issue template to be in line

### CODE REVIEW

**Review by franzTobiasDLR — APPROVED** [review]

**Comment by fmbouga** [comment]
Hello Philipp,

 

I just wait when the runs are completed before finishing the review. I am throwing a look on the file changes. 

 

Kind regards,

Frank

 

Von: Philipp M. Fischer ***@***.***> 
Gesendet: Donnerstag, 17. Oktober 2024 09:57
An: virtualsatellite/VirtualSatellite4-Core ***@***.***>
Cc: Mbouga, Frank Eric ***@***.***>; Review requested ***@***.***>
Betreff: Re: [virtualsatellite/VirtualSatellite4-Core] Added new issue template for hot fix releases (PR #1215)

 

@PhilMFischer <https://github.com/PhilMFischer>  requested your review on: #1215 <https://github.com/virtualsatellite/VirtualSatellite4-Core/pull/1215>  Added new issue template for hot fix releases.

**Comment by fmbouga** [comment]
Hi @PhilMFischer. I saw that the Build and Test for Spotbugs,Surefire and Checkstyle failed. Is it an issue to consider during our review or not obviously.

**Comment by PhilMFischer** [comment]
> Hi @PhilMFischer. I saw that the Build and Test for Spotbugs,Surefire and Checkstyle failed. Is it an issue to consider during our review or not obviously.

@fmbouga For sure the builds should run, otherwise we cannot merge them back into one of our main development lines. Still we allow reviews before everything is perfectly running.

**Review by fmbouga — APPROVED** [review]
- Files change has been check
- Runs are successful 
- Issue template added

**Review by fmbouga — APPROVED** [review]

**Pull request merged**
