### PR TITLE
Adding Jersey and Jetty Dependencies for REST Service

### PR DESCRIPTION
**Pull request by ghost**
Virtual Satellite is planned to provide a REST API. This is implemented with Jetty and Jersey.

- Added Jetty as external Lib (as alternative to the eclipse internal jetty)
- Added Jersey as external Lib
- Added both libs to the external libs feature.

### CODE REVIEW

**Review by dianapeters-dlr — APPROVED** [review]

**Comment by franzTobiasDLR** [comment]
Are there some white-space changes going on? The external lib feature definition file seems to have changed whithout visible changes? Are the line endings still correct?

**Comment by franzTobiasDLR** [comment]
Are there some white-space changes going on? The external lib feature definition file seems to have changed whithout visible changes? Are the line endings still correct?

**Review by franzTobiasDLR — APPROVED** [review]

**Comment by PhilMFischer** [comment]
> Are there some white-space changes going on? The external lib feature definition file seems to have changed whithout visible changes? Are the line endings still correct?

Good question, i will have a look into it.

**Comment by PhilMFischer** [comment]
The linefeeds style between windows and linux changed for the content between the xml statements. Have no clue why. I think we leave it as it is for the time being.

image

**Comment by PhilMFischer** [comment]
Closes #355

**Pull request merged**
